# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/shift/axolotl/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    ImageFv \
    abl \
    aop \
    bluetooth \
    cmnlib \
    cmnlib64 \
    devcfg \
    dsp \
    hyp \
    keymaster \
    modem \
    qupfw \
    storsec \
    tz \
    xbl \
    xbl_config
